apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninja-react-app
spec:
  selector:
      matchLabels:
        app: ninja-react-app
  replicas: 1
  template:
      metadata:
        labels:
            app: ninja-react-app
      spec:
        containers:
        - name: ninja-react-app
          image: vijkum/onboarding:react
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            httpGet:
              port: 8080
              path: /
