kind: Deployment
apiVersion: apps/v1
metadata:
  name: ninja-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ninja-react-app
  template:
    metadata:
      labels:
        app: ninja-react-app
    spec:
      containers:
        - name: ninja-react-app
          image: vijkum/onboarding:react
          imagePullPolicy: Always
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://IPtoreplace:5000"
          ports:
            - containerPort: 80
      restartPolicy: Always
