kind: Deployment
apiVersion: apps/v1
metadata:
  name: ninja-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ninja-react-app
  template:
    metadata:
      labels:
        app: ninja-react-app
    spec:
      containers:
        - name: ninja-react-app
          image: vijkum/onboarding:react
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
