  
apiVersion: v1
kind: Service
metadata:
  name: ninja-react-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: ninja-react-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
